### ISSUE TITLE
Doesn't work in Version 3.2.2

### ISSUE THREAD

**Issue by herrhaase** [florianpnn/sketch-data-parser#4]
Everytime I try to add a JSON ala "{ “label”: “test123” }" nothing happens. Group with $label is set up. Is the plugin still working and if so, maybe you see what i do wrong :)

**Comment by florianpnn** [comment]
There was a lot of changes in the Sketch API since the last update, I'm gonna have a look tonight but I bet you're doing it right ;)

**Comment by herrhaase** [comment]
@florianpnn Any news here? I'm currently working on a template system and could really use this to automate our process :)

**Comment by florianpnn** [comment]
@herrhaase The script is now working for the last Sketch version, if you still don't succeed to make it work send me your file + your JSON and I'll have a deeper look.

**Comment by herrhaase** [comment]
@florianpnn I tried it today, but still no success. I used the latest version and different modifications on the parser, but it is  just not doing anything :(

You can get my file and JSON here http://cl.ly/ZcLP

Is there some console I can use to check what Sketch is doing in the background?

**Comment by florianpnn** [comment]
@herrhaase Okay found where is your problem, you used the wrong double-quote. If I open you JSON with Chrome I get :
```
[
{â€œheadâ€:â€œYUNO WORKâ€, â€œcopyâ€:â€œBecause stupid. Thatâ€™s whyâ€}
]
```
If I write with the good double-quote, I get :
```
[
    {
        "head": "YUNOWORK",
        "copy": "Because stupid. That's why"
    }
]
```
So be sure to use a text editor like Sublime Text or Atom with the highlight syntax you'll quickly spot the difference.
You can see output on the Mac Console but it doesn't give you that much information.
