### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Greghster** [florianpnn/sketch-data-parser#6]
I have tried this exact tutorial and it doesn't work at all. Sketch Version 3.3.3 (12072)
The copy and paste window isnt easy to see what you are putting in either. It would be better with an import json file aswell.
Any possibilities? Thanks:)

**Comment by florianpnn** [comment]
Hey @Greghster !

Could you send me a part of the JSON and an overview of your file (especially the layers)?

FYI : I began to work on an updated version, a preview is available here : https://dribbble.com/shots/2216005-Data-parser

**Comment by Greghster** [comment]
I found the problem, It was the comma at the end of each line. Cant wait for new one!
